Repository zachholcomb/community_compose, pull requests merged in 2020-06, with the labels that each got.

#50 Flash alr
  app/controllers/requests_controller.rb
  app/controllers/sessions_controller.rb
  app/facades/explore_facade.rb
  app/services/flat_service.rb
  spec/features/collaboration/collab_spec.rb
Labels: enhancement

#61 Moved cdn to application layout html to fix load error
  app/views/layouts/application.html.erb
  app/views/scores/index.html.erb
Labels: bug

#69 Consume a microservice we built ourselves
  Gemfile
  Gemfile.lock
  app/facades/explore_facade.rb
  app/models/user.rb
  app/poros/location.rb
  app/services/location_service.rb
  spec/features/microservice/location_spec.rb
  spec/features/scores/schema.rb
  spec/features/scores/score_explore_spec.rb
  spec/fixtures/flat/alt_alt_user_scores.json
  spec/fixtures/flat/alt_user_scores.json
  spec/fixtures/microservice/location.json
Labels: enhancement, location

#88 Jquery andy
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/schema.rb
  spec/features/scores/score_edit_spec.rb
Labels: bug

#89 Last fixes
  app/controllers/users/conversations_controller.rb
  app/views/scores/index.html.erb
  app/views/users/conversations/index.html.erb
  app/views/users/conversations/show.html.erb
Labels: bug
